"""Unified compatibility exports consumed by qubex backend loaders."""

from __future__ import annotations

from qxdriver_quel1.compat import qubex_contract as _qubex_contract
from qxdriver_quel1.compat.exports import (
    DEFAULT_SAMPLING_PERIOD,
    Action,
    AwgId,
    AwgSetting,
    BoxPool,
    CapSampledSequence,
    CapSampledSubSequence,
    CaptureParamTools,
    CaptureSlots,
    ClassificationLineMap,
    ClassificationLineSet,
    Converter,
    GenSampledSequence,
    GenSampledSubSequence,
    LineParam,
    MultiAction,
    NamedBox,
    QubeCalib,
    QuBEMasterClient,
    Quel1Box,
    Quel1ConfigOption,
    Quel1System,
    RunitId,
    RunitSetting,
    Sequencer,
    SequencerClient,
    SingleAction,
    SingleAwgId,
    SingleAwgSetting,
    SingleRunitId,
    SingleRunitSetting,
    SingleTriggerSetting,
    Skew,
    TriggerSetting,
    WaveSequenceTools,
)

__all__ = [
    "DEFAULT_SAMPLING_PERIOD",
    "Action",
    "AwgId",
    "AwgSetting",
    "BoxPool",
    "CapSampledSequence",
    "CapSampledSubSequence",
    "CaptureParamTools",
    "CaptureSlots",
    "ClassificationLineMap",
    "ClassificationLineSet",
    "Converter",
    "GenSampledSequence",
    "GenSampledSubSequence",
    "LineParam",
    "MultiAction",
    "NamedBox",
    "QuBEMasterClient",
    "QubeCalib",
    "Quel1Box",
    "Quel1ConfigOption",
    "Quel1System",
    "RunitId",
    "RunitSetting",
    "Sequencer",
    "SequencerClient",
    "SingleAction",
    "SingleAwgId",
    "SingleAwgSetting",
    "SingleRunitId",
    "SingleRunitSetting",
    "SingleTriggerSetting",
    "Skew",
    "TriggerSetting",
    "WaveSequenceTools",
]

# Import side-effect keeps qubex-facing contract checks active at compat import time.
_ = _qubex_contract
