[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "qxdriver-quel1"
dynamic = ["version"]
requires-python = ">=3.10"
authors = [{ name = "h403", email = "shiomi@ieee.org" }]
maintainers = [{ name = "Akinori Machino" }]
description = "QuEL driver package with qubecalib compatibility"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
dependencies = [
    "numpy >= 1.0",
    "plotly >= 5.0",
    "tqdm >= 4.0",
    "pyyaml >= 6.0",
    "quel_ic_config >= 0.10, < 0.11",
]

[dependency-groups]
dev = ["pyright", "pytest", "ruff"]

[tool.setuptools.dynamic]
version = { attr = "qxdriver_quel.__version__" }

[tool.pytest.ini_options]
addopts = "--import-mode=importlib"
