[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qxdriver_quel"
dynamic = ["version"]
requires-python = ">=3.9"
authors = [{ name = "h403", email = "shiomi@ieee.org" }]
description = "QuEL driver package with qubecalib compatibility"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: GPL",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "numpy >= 1.0",
    "plotly >= 5.0",
    "tqdm >= 4.0",
    "pyyaml >= 6.0",
    "quel_ic_config >= 0.10, < 0.11",
]

[dependency-groups]
dev = ["pytest"]

[tool.setuptools.dynamic]
version = { attr = "qxdriver_quel.__version__" }

[tool.pytest.ini_options]
# cf. https://docs.pytest.org/en/6.2.x/pythonpath.html#import-modes
addopts = "--import-mode=importlib"

[tool.mypy]
ignore_missing_imports = true
